# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
  use_frameworks!

def usePods
    pod 'Alamofire'
    pod 'NVActivityIndicatorView'
    pod 'ReachabilitySwift'
end

target 'CarsApp-MobileExam' do
  usePods
end

